### ISSUE TITLE
Link to DPIN is broken

### ISSUE THREAD

**Issue by mboskin** [covid-alert-ny/covid-green-app#120]
Valerie Shuba at 4:40 on Aug. 27. Build 16. iOS

Link from Help Improve This App to Data Protection Info Notice “ The DPIN could not be loaded.

**Comment by AlanSl** [comment]
That particular link works for me on Android, including after clearing all app data and re-registering. Let's see if anyone else can replicate the problem.

**Comment by mboskin** [comment]
OK. I will let the testing team know.



www.nystec.com<http://www.nystec.com/>

**Comment by AlanSl** [comment]
It's possible there might have been a rare bug that could have been caused by the same issue that caused some text to not change language on choosing a new language. That issue is fixed in https://github.com/project-vagabond/covid-green-app/pull/128 so I'm pretty confident that this should not reoccur in the next build.

@floridemai can you give this link a quick test just to be sure it's not device-specific.

**Comment by mboskin** [comment]
Confirmed fixed by Gajjala, Raghunath
