### ISSUE TITLE
Splash screen is missing on Android

### ISSUE THREAD

**Issue by dharding** [covid-alert-ny/covid-green-app#140]
I am not seeing a splash screen on Android. It shows a blank, purple screen.
Note: I do see a splash screen on iOS

**Comment by floridemai** [comment]
@dharding We're aware of this. I've been sent the following link: https://android.jlelse.eu/the-complete-android-splash-screen-guide-c7db82bce565, but we have yet to choose and implement a solution.
Things to figure out: how do we want to approach it? Is it worth it at this point the time investment against other issues (given it might be a lengthier task... for me at least :)  )

**Comment by AlanSl** [comment]
Since https://github.com/project-vagabond/covid-green-app/pull/152 we show this during app load on Android:

<img width=350 src="https://user-images.githubusercontent.com/29628323/91641390-ed089280-ea1b-11ea-9bab-75afc0104895.jpg" />

It's _technically_ not a splash screen and there is a second or so of flat purple before the branding overlays, but as a long time Android user I'd say this is within ordinary user expectations. All sorts of apps, from the built-in Samsung phone and messages apps to Facebook Messenger on my Note 8 show a second of flat colour initially on loading up from being closed just like this, before a branded loading screen or the initial screen appears. 

Just going through apps now, the only ones I can find that don't start up with a second of flat colour before showing their own branding or initial screen are Google's own in built apps, and these generally just show an enlarged app icon overlaid over a flat colour initially.

**Comment by helloantoine** [comment]
FYI. Today, on Lenovo P2. I see a flat purple screen for 1 s. then the screen above from Alan loads then the page loads.

**Comment by ahurworth** [comment]
I believe this can be closed in favor of https://github.com/project-vagabond/covid-green-app/issues/141

@dharding pls confirm.
