### ISSUE TITLE
Add an Entry Point to the Symptom Tracker from Within the Health Log Tab 

### ISSUE THREAD

**Issue by ahurworth** [covid-alert-ny/covid-green-app#161]
There's a call to action for the user to track their symptoms from the NY COVID Data tab, but not from the My Health Log tab itself (beyond the first day).  We'd like to add one to the My Health Log tab too.  

The Ireland one has this, if we need a reference:

![Screenshot_20200829-180426](https://user-images.githubusercontent.com/68069959/91646888-36f47700-ea22-11ea-8a33-eb62c5507f3f.png)

**Comment by AlanSl** [comment]
I agree and was thinking the same thing while testing the symptoms checker flow yesterday. 

I was planning to talk to @stuartgiles about this on Monday but since you've requested it I've put the basics in for today's build, matching the dashboard link card, so the functionality is there at least. 

We'll probably iterate on the design (e.g. I'm sure Stuart can improve on the double "My Health Log"); for now after today's build (22?), the screen should look like this when a check in is allowed:

<img width=400 src="https://user-images.githubusercontent.com/29628323/91661013-4e3e6d80-ead1-11ea-995c-3857168dcba9.jpg" />

**Comment by helloantoine** [comment]
Looks good to me. 
One detail. Maybe not be specific to this screen but sharing anyway. The margin left, right and top should be the same. On your screenshots it seems bigger for some reason. It would help make more content available and be more consistent as well. Thanks.
![preview](https://user-images.githubusercontent.com/16833643/91706240-06bded00-eb76-11ea-8f88-36c64c26d7f0.png)

**Comment by ahurworth** [comment]
Thanks @AlanSl .  Looking good.

@helloantoine What do you think to removing the word "My Health Log" within the button and re-positioning it below the My Health Log title, but above the collection of Submitted entries?

**Comment by AlanSl** [comment]
If you agree with that suggestion @helloantoine I'll get it done at the same time as the margin adjustements

**Comment by helloantoine** [comment]
Agreed.

**Comment by ahurworth** [comment]
I just reviewed build 22.  Looks good!
