### ISSUE TITLE
The button to allow the user to enter their symptoms should be visible after midnight their time

### ISSUE THREAD

**Issue by ahurworth** [covid-alert-ny/covid-green-app#162]
At the moment the button seems to only appear 24(?) hours after the user's prior entry.  It would be better to allow the user to be able to enter symptoms at any time during their next day, so let's make this any time after midnight, based on their device's local time.

**Comment by AlanSl** [comment]
I believe this is being worked on by @jackmurdoch already as part of the backend work for https://github.com/project-vagabond/covid-green-app/issues/104

**Comment by colmharte** [comment]
@AlanSl the button appearing or not is client side. Jack is not working on this part. Can you fix on app side?

**Comment by AlanSl** [comment]
@ahurworth Can you please confirm which build version of the app you had seen this in? (and is this on Android?)

The behaviour you ask for is how the app has always been designed, however, there was a bug (fixed in build 21, latest build from yesterday) that caused the button to sometimes fail to appear. If you saw this in build 20 or before, it should be working as expected now, in builds 21 and above.

The in-app date check does indeed appear to be unrelated to the ongoing server side date validation work I referred to above, and appears to be working as expected in my tests now (in any device system timezone).

If you have build 21 now, can you please try this test to confirm if the issue still exists:

 - If you don't already have a symptoms check logged for today, please do one
 - Outside of the app in your device's settings, go to Date and Time settings (name may be slightly different depending on device), uncheck the option to automatically set date and time, and set the device date and time to shortly after midnight tomorrow (therefore, next day but less than 24 hours after the previous check)
 - Return to the app. There should now be an option to do a new symptoms check. 
 - (important) After doing this test, please don't forget to go back to the device settings and set it back to setting date and time automatically, so your device's date and time will correct itself (and the option to do another symptoms check should disappear)

**Comment by ahurworth** [comment]
Looks good.  Thanks @AlanSl .
