### ISSUE TITLE
Uploading keys gets intermittent failures on iOS

### ISSUE THREAD

**Issue by dharding** [covid-alert-ny/covid-green-app#277]
Some people are reporting that when they attempt to upload their keys on an iOS device, they get an error. Others have done it successfully. We have not been able to determine under which circumstances this error occurs. We tried a fresh install on a new device that had never used this app or any EN stuff and it had the error. Other devices where TestFlight builds that have been being updated via TestFlight and some worked while others did not.

iOS
builds 1.0.0.25 and 1.0.0.26

![Image from iOS](https://user-images.githubusercontent.com/8274/92062123-f53b3780-ed65-11ea-8d95-c87648def79e.png)

**Comment by dennisgove** [comment]
~This line https://github.com/project-vagabond/covid-green-app/blob/nys/src/services/api/exposures.ts#L123-L134 uses `fetch` instead of `request`. According to Webstorm, `fetch` is undefined and it appears the rest of this file uses `request` instead.~

~The server is correctly returning a response to the POST to `/certificate` but we are not then receiving a POST to `/publish`. I believe this is the line that is erroring out.~

Appears I hadn't properly run `yarn install`. `fetch` is a global and is available.

**Comment by dennisgove** [comment]
It appears that the app call to `/publish` does not include an `Authorization` header. This seems correct because APHL won't be expecting an Authorization header. However, the handler in the backend api is expecting an Authorization header. 

App: https://github.com/project-vagabond/covid-green-app/blob/nys/src/services/api/exposures.ts#L123-L134
API: https://github.com/project-vagabond/covid-green-backend-api/blob/current/lib/routes/exposures/index.js#L232

If a header isn't found it will throw `Unauthorized` (https://github.com/project-vagabond/covid-green-backend-api/blob/current/lib/plugins/jwt/index.js#L5-L23)

What's troubling is I'm not seeing any logs for the calls to `/publish`.

**Comment by colmharte** [comment]
The calls to /publish go to APHL not our server. 
There are 2 reasons this was happening
1) Codes generated with no onsetDate
2) A repeat upload to APHL from the same phone will fail

PR opened to fix #2

**Comment by dennisgove** [comment]
> The calls to /publish go to APHL not our server.
> There are 2 reasons this was happening
> 
>     1. Codes generated with no onsetDate
> 
>     2. A repeat upload to APHL from the same phone will fail
> 
> 
> PR opened to fix #2

I saw failures in two forms.

1. Went through the full upload process on my iPhone. I used PostMan to generate a verification code - that request contained an `onsetDate` and that onsetDate value was saved to the database. The first time everything went through but it failed the second time I tried to upload (a few hours later). This is clearly issue 2.

2. Went through the full upload process on my wife's iPhone. She'd never had the App installed until 1 hour before I tried to upload. This was the first time any upload occurred from her phone. I generated a verification code in the exact same way (with an `onsetDate`) and went through the process. The upload failed. This is neither issue 1 or 2.

**Comment by AlanSl** [comment]
@dennisgove on your wife's phone, were COVID alerts set up and enabled with a green tick on My COVID Alerts when you uploaded the codes?

**Comment by colmharte** [comment]
If no keys available APHL call will also fail. @dennisgove sounds like the issue you ran into. We will create a PR to cater for this.

**Comment by dennisgove** [comment]
I'd expect a phone with Exposure Notification turned on for an hour to have at least 1 key to upload.

**Comment by dennisgove** [comment]
> @dennisgove on your wife's phone, were COVID alerts set up and enabled with a green tick on My COVID Alerts when you uploaded the codes?

Yes. I went through the NY app setup process around 8:15p, and turned on the exposure notification system at that time. About an hour later I tried going through the key upload process using a valid code generated via Postman (with an associated `onsetDate`)

**Comment by dennisgove** [comment]
Is it possible that when getting keys from iOS, the phone doesn't return keys less than 4 hours old (to prevent us from uploading still active or too new keys)? I recall that part of the documented rules indicate that keys should have a certain age and perhaps no longer be active.

**Comment by dennisgove** [comment]
> Is it possible that when getting keys from iOS, the phone doesn't return keys less than 4 hours old (to prevent us from uploading still active or too new keys)? I recall that part of the documented rules indicate that keys should have a certain age and perhaps no longer be active.

@dharding says this has been corrected by checking for 0 keys before trying to upload. If 0 keys the upload is skipped.

**Comment by dennisgove** [comment]
> It appears that the app call to `/publish` does not include an `Authorization` header. This seems correct because APHL won't be expecting an Authorization header. However, the handler in the backend api is expecting an Authorization header.
> 
> App: https://github.com/project-vagabond/covid-green-app/blob/nys/src/services/api/exposures.ts#L123-L134
> API: https://github.com/project-vagabond/covid-green-backend-api/blob/current/lib/routes/exposures/index.js#L232
> 
> If a header isn't found it will throw `Unauthorized` (https://github.com/project-vagabond/covid-green-backend-api/blob/current/lib/plugins/jwt/index.js#L5-L23)
> 
> What's troubling is I'm not seeing any logs for the calls to `/publish`.

and from Slack discussion

> we shouldn't check auth header on our /publish endpoint

@jackmurdoch @colmharte were you able to get a PR in for this change?

**Comment by colmharte** [comment]
Can we close this issue as the 0 keys was addressed.
