### ISSUE TITLE
Could not generate proximity alerts

### ISSUE THREAD

**Issue by bonniejohn** [covid-alert-ny/covid-green-app#334]
I tried to generate proximity alerts today with two iPhones, but the experiment failed.
At 9/4/2020 12:34 EST, I entered a Positive Test code into an iPhone SE (1st gen), 13.7, build 30 (the share succeeded).
The phone it had been near continuously for serval hours prior was a iPhone SE (1st gen), 13.6.1, build 30.
At 9/4/2020 12:34 EST, I entered a different Positive Test code into the iPhone SE (1st gen), 13.6.1, build 30 (the share succeeded). The phone it had been near continuously for serval hours prior was the iPhone SE (1st gen), 13.7, build 30.
Neither phone got a proximity alert as of 7:50 pm EST.

**Comment by dennisgove** [comment]
I've been looking through the https://github.com/covidgreen/react-native-exposure-notification-service project and noticed a couple things. I'm not well versed in Swift so I may be misunderstanding some of the background processing going on, but it appears there is a case where exposure checking fails and never runs again until the app is restarted.

The [`ExposureProcessor::scheduleCheckExposure`](https://github.com/covidgreen/react-native-exposure-notification-service/blob/current/ios/ExposureProcessor.swift#L285-L297) method contains a catch block that logs a failure to schedule exposure checking but does not do anything to retry.

If the exposure check was scheduled and completes another exposure check is scheduled via the [`lastOperation.completionBlock](https://github.com/covidgreen/react-native-exposure-notification-service/blob/current/ios/ExposureProcessor.swift#L265-L270).

However, because of the catch and no retry in `ExposureProcessor::scheduleCheckExposure` I think that if there is an error when scheduling an exposure check then exposure checks will never be retried. This is because the rescheduling of an exposure check requires the succesfull scheduling and completion of the previous exposure check.

The original kicking off of this queue loop is done from [`ExposureProcessor::registerBackgroundProcessing`](https://github.com/covidgreen/react-native-exposure-notification-service/blob/current/ios/ExposureProcessor.swift#L242-L251) which, if I'm following react-native code correctly is called from `AppDelegate::didFinishLaunchingWithOptions` which contains these lines
```
  [ExposureNotificationModule registerBackgroundProcessing];
  [super application:application didFinishLaunchingWithOptions:launchOptions];
```
This is run when the app starts running.

**Comment by dennisgove** [comment]
This morning my wife's phone got the following alert. The alert says that on Aug 31st our iPhones were in proximity. Sounds reasonable, but my wife's phone didn't have the app installed or the Exposure Notification System turned on until Sept 2nd. There's no way she had one of my RPIs from Aug 31st. I think the dates are wrong.

![proximity-alert](https://user-images.githubusercontent.com/654519/92297734-4555fd80-ef10-11ea-9d6e-0b04c8f76679.jpg)

**Comment by colmharte** [comment]
Uploads contain keys from yesterday and backwards but not today's key.
This needs to be factored in when testing on iOS devices.

**Comment by fahd-arshad** [comment]
To clarify: on iOS devices (and possibly also Android), alerts do not fire if the devices are only in proximity on the day of alert and not on the prior days.

@colmharte: please confirm that I am right. If so, multiple instances of outright test failures on our side (but not the delays) would be explained by this. We can then downgrade/close this issue. 

If you can point us to the A/G docs and any progress by A/G to change this, we would appreciate it. I for one do not understand the epidemiological reasons for this limit.

**Comment by colmharte** [comment]
@fahd-arshad yes this is correct, I sent you an email yesterday with extracts from apple and google docs on this.

**Comment by AlanSl** [comment]
@fahd-arshad Can you check the documents sent and re-triage accordingly if you are satisfied that they explain the test results seen?

**Comment by AlanSl** [comment]
@fahd-arshad Are you happy that this can be closed now after the rounds of testing done since it was opened?
