### ISSUE TITLE
Share Icon and Text Incorrect

### ISSUE THREAD

**Issue by kevin-sheldon** [covid-alert-ny/covid-green-app#36]
iPhone X, iOS 13.6, text size set to 3rd stop from the left, TestFlight build 1.0.0 (4)

Scope: Onboarding Screens

Issue: When you click on the Share Icon, or the button to Share the App, the icon and associated text on the iOS screen are incorrect. Should display the NYS COVID App icon and text. See attached screenshot. 
<img width="400" alt="Share Icon" src="https://user-images.githubusercontent.com/69158966/90783752-7efef580-e2ce-11ea-9b20-f4abf296f60f.png">

**Comment by AlanSl** [comment]
I'm setting this as `low` because the text changes have been done which is the main part. 

For the icon, I've got an open PR that does that here https://github.com/project-vagabond/covid-green-app/pull/171 - I don't want to merge it right now because it adds a dependency that adds a lot of native code that I'd like to test more than I currently have time to.

**Comment by helloantoine** [comment]
Hi @AlanSl. 
Not sure if it's still work in progress. I do see the updated text in iOS but not in Android. iOS icon still missing.

![Image from iOS (5)](https://user-images.githubusercontent.com/16833643/92006681-f73cd080-ed3c-11ea-94dc-78a0e53a7bfe.png)

![screenshot_20200902-164054_android_system](https://user-images.githubusercontent.com/16833643/92007044-5864a400-ed3d-11ea-8b4e-bb3f2b3845b1.png)

@ahurworth
