### ISSUE TITLE
App Crashes on attempting to turn on closeness sensing

### ISSUE THREAD

**Issue by mboskin** [covid-alert-ny/covid-green-app#388]
App was running fine on update, deleted data to test onboarding and now the app will not complete onboarding. Appears to crash immediately after attempting to turn on closeness sensing

Bug 31 |   | Build/Release 1.0.0 (33) | Android | Galaxy S10+ | 9/8/20 4:43 PM | Patrick Brennan

**Comment by AlanSl** [comment]
Several of us have tried to replicate this and can't. Looking at the history around build 33 and the steps described, it's very likely this was fixed in https://github.com/project-vagabond/covid-green-app/pull/365 and https://github.com/project-vagabond/covid-green-app/pull/370 and will have been fixed since build 34.

**Comment by mboskin** [comment]
Given the following, this is closed. Several of us have tried to replicate this and can't. Looking at the history around build 33 and the steps described, it's very likely this was fixed in #365 and #370 and will have been fixed since build 34.
