### ISSUE TITLE
Bug Onboarding screens displayed multiple times issue

### ISSUE THREAD

**Issue by helloantoine** [covid-alert-ny/covid-green-app#411]
**Issue** Multiple Done screens or stuck in the flow
**Steps:** Delete your data, then do onboarding again and tap quickly on the buttons. :)

[onboarding done screen duplicated.zip](https://github.com/project-vagabond/covid-green-app/files/5209156/onboarding.done.screen.duplicated.zip)

@ahurworth

**Comment by AlanSl** [comment]
Done in https://github.com/project-vagabond/covid-green-app/pull/414 and so should be fixed in next build.

The issue was actually a lot simpler than it looked: the loading spinner was getting cancelled early due to an uneccessary clearing of app data before beginning registration. Since https://github.com/project-vagabond/covid-green-app/commit/ce0f1b5c051a734262225a871a94f8c1fa0f03ac we clear absolutely everything when we clear app data - but this also cleared the flag that the app is loading, cancelling the loading spinner and overlay almost as soon as it appears. 

Because registration takes a few seconds, everyone was re-pressing the button when the loading indicator and disabling of the buttons spuriously disappeared, queuing up multiple registration attempts. These complete several seconds later, bombarding the user with a barrage of unexpected navigation events, making the app appear broken.

We don't need to clear app data before registration, so we removed that. The spinner doesn't disappear, registration is slightly faster, and it's back to being impossible for the user to repeatedly press the button and bombard themselves like this.

**Comment by helloantoine** [comment]
So I got spinner for a while, but it worked. Thx
