### ISSUE TITLE
Need internal jump menu

### ISSUE THREAD

**Issue by fahd-arshad** [covid-alert-ny/covid-green-app#49]
For QC purposes, we need an "internal" menu to jump to the screens/states that are otherwise inaccessible, such as proximity alerts, positive cases, error conditions, etc.

**Comment by fahd-arshad** [comment]
@mboskin the debug menu allows access to the Exposure UI flows now including the alert (I tested build 22 on iOS). Is this enough for NYS? Currently you can't get to the error conditions directly. If you need this for QA, bump up the priority accordingly.

**Comment by mboskin** [comment]
Kevin,

This is your decision, not mine. Issue #49 (filed by Fahd) is:
“For QC purposes, we need an "internal" menu to jump to the screens/states that are otherwise inaccessible, such as proximity alerts, positive cases, error conditions, etc.”

Their response is:

“the debug menu allows access to the Exposure UI flows now including the alert (I tested build 22 on iOS). Is this enough for NYS? Currently you can't get to the error conditions directly. If you need this for QA, bump up the priority accordingly.”


_____________________

**Comment by fahd-arshad** [comment]
Removing from Launch until we have a business decision on whether this is needed for launch or not. I suspect not at this poitn.

**Comment by davidjharding** [comment]
Closing since this is of limited value at this point.
