### ISSUE TITLE
NYC HOTLINE INFO NEEDS TO BE ADDED **CRITICAL**

### ISSUE THREAD

**Issue by kevin-sheldon** [covid-alert-ny/covid-green-app#524]
We need to add a New York City Hotline number to the app in addition to the New York State hotline number. 

For each place that the NYS hotline number appears in the app:

1) Exposure Notification Screen
2) Learn how to keep others safe screen
3) Submit feedback screen

The exact text needs to be included underneath the existing messages:

For NYC: Call the Test & Trace COVID Hotline for more information or to find a NYC test site.
212-COVID19 (212-268-4319) 

The phone number in parenthesis needs to be clickable just like the NYS hotline number. 

We understand that this will require a new submission to Apple and Google. +David Harding

**Comment by kevin-sheldon** [comment]
When this is built, can you please send screenshots to @fahd-arshad  and I as soon as this is completed?

**Comment by AlanSl** [comment]
@fahd-arshad and @kevin-sheldon ready to go wtih your approval and tested on screen readers. Note there are four places where the NYS hotline appeared: the three listed above, plus symptoms checker results if symptoms are reported:


<img width=350 src="https://user-images.githubusercontent.com/29628323/94414762-a02bef00-0174-11eb-8a4d-adf1311a11f9.png" /> <img width=350 src="https://user-images.githubusercontent.com/29628323/94414763-a0c48580-0174-11eb-84dd-006173d68cff.png" /> <img width=350 src="https://user-images.githubusercontent.com/29628323/94414788-a91cc080-0174-11eb-944e-457925019f92.png" /> <img width=350 src="https://user-images.githubusercontent.com/29628323/94414790-a9b55700-0174-11eb-9cdc-f9f845b8bc3b.png" />

This is added in English only - <strike>let me know if you want this English text added to non-English languages (since I assume there isn't time for the translators to get back to us for this release?)</strike> I was just added to the email thread about translations, keep me updated and I'll add them ASAP

**Comment by AlanSl** [comment]
<strike>I'm starting a new build with the above in English, so that if you're happy with it we can get resubmitting the app ASAP - ping me on Slack if you come online before it's complete (around 06:30-07:00ish NY time) and want something changed.</strike>

[edit] I was just informed that translations have been requested so we'll wait to hear on the status there before doing a build.

**Comment by kevin-sheldon** [comment]
Adding translations file for all languages. 
[Rush Line for NYS DOH.docx](https://github.com/project-vagabond/covid-green-app/files/5293366/Rush.Line.for.NYS.DOH.docx)

**Comment by AlanSl** [comment]
These are all now added and I'm starting a build to include them. 

Translation screenshots here https://github.com/project-vagabond/covid-green-app/pull/527#issuecomment-700054128 (I'll add Bengali screenshots in around 5 minutes)

**Comment by AlanSl** [comment]
Chinese:

<img width=175 src="https://user-images.githubusercontent.com/29628323/94446989-3bd35480-01a1-11eb-8417-3e9afe7f95fe.jpg" /><img width=175 src="https://user-images.githubusercontent.com/29628323/94446993-3d048180-01a1-11eb-9ddc-56b602e11957.jpg" /><img width=175 src="https://user-images.githubusercontent.com/29628323/94446997-3d9d1800-01a1-11eb-91f1-261d98649da1.jpg" /><img width=175 src="https://user-images.githubusercontent.com/29628323/94446998-3e35ae80-01a1-11eb-8699-030f29498e41.jpg" />
Haitian:

<img width=175 src="https://user-images.githubusercontent.com/29628323/94446999-3e35ae80-01a1-11eb-9643-7cc38c5498fe.jpg" /><img width=175 src="https://user-images.githubusercontent.com/29628323/94447000-3ece4500-01a1-11eb-88dc-ec16a08c4cf2.jpg" /><img width=175 src="https://user-images.githubusercontent.com/29628323/94447003-3f66db80-01a1-11eb-9b50-8d0530c506c9.jpg" /><img width=175 src="https://user-images.githubusercontent.com/29628323/94447007-3f66db80-01a1-11eb-84da-9cd65b701765.jpg" />
Korean:

<img width=175 src="https://user-images.githubusercontent.com/29628323/94447009-3fff7200-01a1-11eb-816a-a276a9dfc9c8.jpg" /><img width=175 src="https://user-images.githubusercontent.com/29628323/94447011-40980880-01a1-11eb-8bb8-c9264d3e76e6.jpg" /><img width=175 src="https://user-images.githubusercontent.com/29628323/94447012-40980880-01a1-11eb-9975-fc82bd8fb9a6.jpg" /><img width=175 src="https://user-images.githubusercontent.com/29628323/94447013-41309f00-01a1-11eb-9dde-b4f04161a0a6.jpg" />
Russian:

<img width=175 src="https://user-images.githubusercontent.com/29628323/94447014-41c93580-01a1-11eb-8374-0494e6035107.jpg" /><img width=175 src="https://user-images.githubusercontent.com/29628323/94447017-41c93580-01a1-11eb-887c-df0b7bd98c79.jpg" /><img width=175 src="https://user-images.githubusercontent.com/29628323/94447019-4261cc00-01a1-11eb-8981-e5add5347560.jpg" /><img width=175 src="https://user-images.githubusercontent.com/29628323/94447021-42fa6280-01a1-11eb-9004-b2df6f665ca0.jpg" />
Spanish:

<img width=175 src="https://user-images.githubusercontent.com/29628323/94447026-42fa6280-01a1-11eb-8d6b-9c836c46e750.jpg" /><img width=175 src="https://user-images.githubusercontent.com/29628323/94447029-4392f900-01a1-11eb-8c4d-2fd189a68e6f.jpg" /><img width=175 src="https://user-images.githubusercontent.com/29628323/94447033-442b8f80-01a1-11eb-95a8-2bbe3a487cc3.jpg" /><img width=175 src="https://user-images.githubusercontent.com/29628323/94447038-442b8f80-01a1-11eb-841c-efc643094c38.jpg" />

Bengali:

<img width=175 src="https://user-images.githubusercontent.com/29628323/94455601-2c590900-01ab-11eb-814c-4ffcf07729f3.jpg" /><img width=175 src="https://user-images.githubusercontent.com/29628323/94455592-2a8f4580-01ab-11eb-910a-25c30ab3f546.jpg" /><img width=175 src="https://user-images.githubusercontent.com/29628323/94455595-2bc07280-01ab-11eb-9d1e-7039c4cfa2c4.jpg" /><img width=175 src="https://user-images.githubusercontent.com/29628323/94455599-2bc07280-01ab-11eb-98eb-05da703d2ab8.jpg" />

**Comment by kevin-sheldon** [comment]
Confirmed in Build 49
