### ISSUE TITLE
Should symptoms be deleted after uninstall and reinstall?

### ISSUE THREAD

**Issue by denisedresbach** [covid-alert-ny/covid-green-app#562]
App version: iOS 1.1.0.52
OS: iOS 14
Device: iPhone SE
Reproducible: Always

Summary: App with symptom history does not get deleted on uninstall. Should it?

Steps to reproduce:

1. Install app (TestFlight) and add symptoms
2. Uninstall app
3. Install again and onboard
4. Go to My health log

Actual Results: Symptoms from before are shown

**Comment by AlanSl** [comment]
No it shouldn't, and this is something we'd been meaning to change.

@denisedresbach This is a tricky but particularly important one to test because the first time a user loads up the app after updating we move their symptom history from a type of storage that persists after uninstall to a type that doesn't - and we want to be absolutely sure this transfer can't fail causing users to lose their symptoms history on updating the app.

As well as testing that it doesn't persist after uninstall, please can you make sure you have some symptoms checker history before updating to 1.1.0.53, then check that it **is** all present and correct after updating, including after closing and reopening the app after updating. 

Where possible, especially if you can do the update from a previous version to 1.1.0.53 multiple times, can you please see if you can find any way of messing up the process after updating such that your symptoms history gets lost (e.g. turning the phone off while the app loads, that sort of thing). It _should_ be impossible...

**Comment by denisedresbach** [comment]
@AlanSl Ok sounds good I will do this testing. Thank you for the info!

**Comment by denisedresbach** [comment]
Testing notes:

iOS
1. Update with symptoms - Verify symptom history is still there after update ---PASSED 
Installed Previous build 1.0.2.51 and checked in with symptoms, after updating to 1.1.0.53 I still see my symptom history.
2. Uninstall and reinstall with symptoms - Verify that the symptoms are cleared when reinstalling ---PASSED
3. Update and try to disrupt multiple ways to verify symptoms are not lost ---PASSED

Android 
1. Update with symptoms - - Verify symptom history is still there after update ---I don't think I can test this one since I cannot go back a version like iOS? BLOCKED
2. Uninstall and reinstall with symptoms - Verify that the symptoms are cleared when reinstalling ---PASSED
3. Update and try to disrupt multiple ways to verify symptoms are not lost ---BLOCKED I cannot test updates with test Android

**Comment by AlanSl** [comment]
@denisedresbach Do you have any Android devices used only for testing where you can add and remove Google accounts without any problems? 

If so can you try this please on that one device:

 - Uninstall Covid Alert NY 
 - Remove the Google account linked to the NYS beta testers program from the device in device accounts settings (if that was the only Google account either add a different one or set up a basic google account for this)
 - Install the public Covid Alert NY from the normal (non-beta) Google Play store
 - Set it up, add some symptoms history, make a note or take a screenshot of the symptom history
 - Re-add the Google account linked to the NYS beta testers program to the device in device accounts settings
 - Update the app when the Google Play Store listing for Covid Alert NY shows as being linked to internal testing and an update becomes available (I think this happens almost immediately but there might be a delay of up to 24 hours like when an account is linked)
 - Check the app is now the right version and check the symptom history is unchanged.
 - Re-open the app and check it's still unchanged
 - Add another symptom check-in and check that the symptom history is as expected

Thanks!

**Comment by denisedresbach** [comment]
Hi @AlanSl I only have the one Android device and it is my personal device. The linked Google account is my main account unfortunately. Also, I thought if we go from public app to a test app it will make me re onboard. At least that is what I found with the other apps. I was told that was the reason. Is that not true for this one?

**Comment by AlanSl** [comment]
Ah okay, didn't know that about switching types of app. In that case we can't test this beyond what I was doing locally which all worked fine so it should be fine to close this
