### ISSUE TITLE
Sometimes my app icon turns into this black and white icon

### ISSUE THREAD

**Issue by denisedresbach** [covid-alert-ny/covid-green-app#564]
App version: iOS 1.1.0.52
OS: iOS 14
Device: iPhone SE
Reproducible: Not seen until today afternoon

Summary: My app icon changed to a black and white icon

Steps to reproduce: I am not sure how to repro this. I was doing some uninstall and install testing including updating from previous build 1.0.2 (51) and now my icon looks like this. I have restarted and reinstalled and it seems to get fixed but then goes back to this missing icon state. Any advice on what I should look at that might be causing this?

![IMG_0360](https://user-images.githubusercontent.com/69995161/97511085-6b61b200-1943-11eb-9b26-f8fa7d240ab7.PNG)

**Comment by AlanSl** [comment]
@denisedresbach We can't replicate this either and haven't seen any other reports of it. Did you find any way of replicating it, does it still happen, and have you seen it since? 

And to confirm - was this on a build from Testflight and not from the public App Store? Have you ever seen this with any of the latest public releases?

**Comment by denisedresbach** [comment]
@AlanSl I have not seen this since but I have not been testing NY lately. My icon is fine at the moment. This was a build from TestFlight and I was doing update testing and install testing over and over again. I was using the previous build in Test Flight to do updates. I will watch for it for sure when I am testing NY again. I can reopen this if I see it.
