### ISSUE TITLE
Changing from RTL to LTR shows the exposure alert 

### ISSUE THREAD

**Issue by denisedresbach** [covid-alert-ny/covid-green-app#596]
App version: Android 1.1.1.61 
OS: Android 11
Device: Pixel 3XL
Reproducible: Always

Summary: Changing from RTL to LTR shows the exposure alert 

Steps:
1. Launch app and go to Settings > Debug 
2. Simulate exposure and view notification alert
3. Go to Settings > Language 
4. Change from English to Arabic and watch the screen for a few seconds

Results: Language changes as desired, but after a few seconds the Alert pops up
Expected: I would expect it to stay on the language screen not jump to alert

**Comment by denisedresbach** [comment]
I also see this happen if - I get an exposure alert (using simulator), complete original steps above, delete data and without restarting the app I onboard and change language again. The exposure alert pops up but this time with no date.
Workaround is to delete data, restart app completely, onboard and then change language.

**Comment by AlanSl** [comment]
@denisedresbach  Does this definitely only happen when there is a valid, active exposure alert, and only after pressing a notification, and only on Android?

If yes to those, I know what this is, I saw it while working on the RTL feature. It'd be a lot of delicate and potentially risky work to stop this happening because it's a result of the way the exposure alert status is stored in the Android app intent so that on opening the app from a notification, the app can store that the alert should be shown before everything loads then show it after everything is ready. 

I figured that if a user has an exposure alert and then chooses to change the app language, taking them to the new translation of what will for them be the most important screen in the app is not harmful, and is better than risking creating a more serious bug case where a user might not be taken to the exposure alert screen on pressing the notification in some hard to anticipate edge case.

**Comment by denisedresbach** [comment]
@AlanSl Yes, this appears to only happen once you press notification on an alert. 
I tried changing the language both before an alert and after an alert without pressing notification. For both of these I do not see the exposure alert after changing the language. Once I press the notification and then change language, it shows that alert.

I am not able to reproduce this on iOS only Android.

It does seem like a strange flow, but I agree with you that it is not harmful as it is and an edge case. I suppose it can just be a known issue?
