### ISSUE TITLE
Cache app settings and data and use when offline

### ISSUE THREAD

**Issue by AlanSl** [covid-alert-ny/covid-green-app#607]
@denisedresbach this is already done in https://github.com/covid-alert-ny/covid-green-app/pull/605 and will be in the next build (63?), if it is working then the user-visible change should be:

 - If the app has been opened then is re-opened while the server is unavailable (e.g. no internet):
   - On the dashboard, the charts would show with data cached from last time the app is open instead of being missing
   - On the data policy screen, the data policy from last time the app was open should show instead of a message that it couldn't be loaded

When internet is available the charts should update with new data on refresh as before.

**Comment by denisedresbach** [comment]
@AlanSl When I disconnect from the network and reopen the app or refresh the app that is open, I no longer see the message that tells me to check my internet connection. Is that expected now with this change?
1.1.1.64

**Comment by denisedresbach** [comment]
1.1.1.67
I can verify that the old data and data policy shows when offline.  I cannot verify if when coming back online, that the new data refreshes. This is because of #595.

**Comment by denisedresbach** [comment]
1.1.1.69 iOS - I left my phone in airplane mode overnight. When it went offline the data was up to Jan 19th. Next day I see Android has Jan 20th so I put iPhone back online and refreshed the screen a few times. I still see Jan 19 as latest date. I tried quitting app and starting up again and it still doesn't refresh for me. I updated to 1.1.1.71 and now it says Jan 20.

**Comment by denisedresbach** [comment]
1.1.1.71 iOS shows old data if offline and updates after being put back on.
I disconnected the iPhone Friday evening from the internet by putting in airplane mode. Data was showing Jan 21 and as it was offline for a couple days it still showed the data for 21st. Monday 25th I put it back online and refreshed the data screen. Results are that it updated to latest Jan 23rd. I cannot test this on Android since I don't have something that I can have offline for a day but I was able to test that it shows something on both data and policy screens if device is offline.
