### ISSUE TITLE
Add a submit button to code upload screen

### ISSUE THREAD

**Issue by AlanSl** [covid-alert-ny/covid-green-app#612]
Done in https://github.com/covid-alert-ny/covid-green-app/pull/611

- User should be able to input a code and press a button to manually have it validated (e.g. to explicitly see if a 6-digit code was invalid or inputted incorrectly)
- If a user enters a valid code it should validate itself automatically without interrupting the user (to be sure we're not introducing any usability obstacles to users inputting their codes - should be in no way more difficult than before)
- Should be accessible on iOS and Android and usable on any screen size / user setting, and normal tasks like correcting an incorrectly inputted code should be easy and natural

**Comment by denisedresbach** [comment]
Testing status for NY app with https://github.com/covid-alert-ny/covid-green-app/issues/612
I have a few questions and wrote up a few tickets in backlog.
?'s
I can test codes from Postman that are 8 characters and from text that are 16 (numbers and letters). Is there a way for me to get a 6 digit code that is valid?
I can only add up to 8 characters when sharing a code. The test I receive has 16 numbers and letters. Will anyone need to enter that 16 code manually?
Should I be able to paste the 16 characters from a text and share codes that way? When I paste 16 characters it enters 2 characters.
Entered one ticket for all issues seen with TalkBack and VoiceOver. Let me know if you want those all separated out to individual tickets.
Existing issues still seen:
Still getting error on upload valid codes
Data on NY COVID Data screen is still old - Latest is December 7th

**Comment by denisedresbach** [comment]
1.1.1.69 Tested this over multiple builds and continuing to close tickets. 
The main points here are complete.
Enter valid 8 or 16 characters and it auto validates it.
If invalid you press the button and it will tell you it is invalid.
Testing was done on different sizes and with screen readers from Android and iOS - some VoiceOver issues are left open 

Regarding my questions above:
I can only do 8 and 16 characters that are valid and that seems to be a limitation to testing but ok.
I can enter the 16 manually and I can paste it.
I can upload (not doing it now since it is prod) but I was able to last build
Data on NY COVID Data screen is updated now
