### ISSUE TITLE
If app is not installed and I click on link with code, it takes me to turning on exposure notifications

### ISSUE THREAD

**Issue by denisedresbach** [covid-alert-ny/covid-green-app#615]
App version: 1.1.1.64
OS: iOS 14.2, Android 11
Device: iPhone SE, Pixel 3 XL
Reproducible: Always

Summary: If app is not installed and I click on link with code it takes me to turning on exposure notifications. I assume this is out of our control at this point. Maybe the text can have a message in it that tells them what to do if they haven't installed?

Current text I receive: 
Your Exposure Notifications verification link: https://us-ny.en.express/v?c=2a2qy691f6vxwz5a Expires in 24 hours (click for mobile device only)

**Comment by AlanSl** [comment]
For me, if the app's not installed, on both Android and iOS the link opens the Play Store or App Store entry for Covid Alert NY.

@colmharte do you know if there difference might be geographical e.g. if @denisedresbach  is in a region where en-express is active and I'm not? Either way I'm not sure if this is under our control?

**Comment by AlanSl** [comment]
@denisedresbach  Discussed with Colm on Slack - sounds like this is out of our control and not-wrong behaviour, but I'm curious about why it's different on yours to mine. My hunch is that it's because of EN Express availability in your region: for you it recognises that you can enable EN Express and tries to start that, and doesn't for me since that's not available here.

- Does it go to settings like this on all of your devices?
- What's in your "other available apps" list on the devices that do this?
- Are you in a location where there is an EN Express app available? I can't find an up to date list but I think Washington State and California use EN Express but the Canada app doesn't

**Comment by AlanSl** [comment]
Okay so based on Slack discussion it looks like the difference is that you're in a location with EN Express. So it looks like this is just the expected system behaviour and we can close this
