### ISSUE TITLE
Message on Share close contact screen says enter the 8-digit number, Is this ok since we can enter 6 and it is 16 from link?

### ISSUE THREAD

**Issue by denisedresbach** [covid-alert-ny/covid-green-app#616]
App version: 1.1.1.64
OS: iOS 14.2, Android 11
Device: iPhone SE, Pixel 3 XL
Reproducible: Always

Summary: Message on Share close contact screen says enter the 8-digit number, Is this ok since we can enter 6 and it is 16 from link?

![2021-01-18](https://user-images.githubusercontent.com/69995161/104979243-a3afe400-59b8-11eb-8c17-9f0002027984.png)

**Comment by AlanSl** [comment]
This depends on whether there will be a a period when the new release is out but 6-digit codes are still being dispatched: @colmharte ?

**Comment by AlanSl** [comment]
We discussed this on Slack - there might be a two-week period where the new app is out and 6-digit codes are still being issued so it'll say "6 to 8 digit" then this will switch to "8-digit" when we disable 6 digit codes from the server. Only in English since the timing doesn't work for getting translations.

Wording tweak should be in the next build.

No need to mention 16 digit codes since we're not expecting users to type them in, they should be coming direct from the link.

**Comment by denisedresbach** [comment]
Verified it now says: "Please enter the 6 or 8 digit number that the public health representative has given you over the phone or texted to you:"
