### ISSUE TITLE
No longer see the internet connection message when offline 

### ISSUE THREAD

**Issue by denisedresbach** [covid-alert-ny/covid-green-app#622]
Separating from https://github.com/covid-alert-ny/covid-green-app/issues/607 so it doesn't get lost

When I disconnect from the network and reopen the app or refresh the app that is open, I no longer see the message that tells me to check my internet connection. Is that expected now with this change?
1.1.1.64

**Comment by AlanSl** [comment]
This should already be fixed in https://github.com/covid-alert-ny/covid-green-app/commit/e4c2b8da171279962733a75905e5ced4cabfae7a which came after the previous build before today's new build(s).

There is a small change of behaviour though - the error only shows when the app tries to load some data (matching the dashboard message wording, "We were not able to load some of the data correctly"). Previously we used a library to respond when the device wasn't connected without needing to try to download anything but it proved to be unreliable and incorrect on some devices so it's only now when an actual attempt to load data fails, e.g. refresh app or pull down to refresh.

**Comment by denisedresbach** [comment]
Verified now I get Connection message: Please check your internet connection and try again. 1.1.1.67
